[workspace]
members = [
    "call-home",
    "console-logger",
    "exporter",
    "operators",
    "k8s/plugin",
    "k8s/proxy",
    "k8s/supportability",
    "upgrade-job",
]

exclude = [ "./dependencies/control-plane" ]
