name: Main Helm Chart
on:
  push:
    branches:
      - github-actions-test
    paths:
      - 'chart/**'

jobs:
  main-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./scripts/helm/shell.nix
      - name: Update loglevel to debug
        run: |
          sed -Ei "s~(logLevel: .*)~logLevel: debug~" chart/values.yaml
      - name: Check if the chart is publishable
        run: |
          branch="${{ github.ref_name }}"
          nix-shell --pure --run "./scripts/helm/publish-chart-yaml.sh --check-chart "$branch"" ./scripts/helm/shell.nix
      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: ${{ secrets.PLAYING_GOD }}
          charts_dir: chart
          charts_url: https://niladrih.github.io/github-actions-test
          owner: niladrih
          repository: github-actions-test
          branch: gh-pages
